<a href="https://colab.research.google.com/github/Sunny-Janjua/data_analysis-/blob/main/class_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array=np.array([1,2,3,4,5])

In [3]:
array

array([1, 2, 3, 4, 5])

In [5]:
array.shape

(5,)

In [6]:
array.size

5

In [7]:
array.dtype

dtype('int64')

In [11]:
array=np.zeros((5,5))

In [12]:
array=np.array([1,2,3,4,5,6,7,8])

In [13]:
array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
newarray=np.zeros((5,5))

In [15]:
newarray

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
newarray=np.ones((5,5))

In [17]:
newarray


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
newarray=np.full((5,5),6)

In [21]:
newarray

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [23]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
# Output: [1 2 3 4 5]


[1 2 3 4 5]


In [24]:
zeros_arr = np.zeros((2, 3))  # 2x3 array
print(zeros_arr)
# Output: [[0. 0. 0.]
#          [0. 0. 0.]]


[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
ones_arr = np.ones((3, 2))
print(ones_arr)
# Output: [[1. 1.]
#          [1. 1.]
#          [1. 1.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
full_arr = np.full((2, 2), 7)
print(full_arr)
# Output: [[7 7]
#          [7 7]]


[[7 7]
 [7 7]]


In [27]:
newarray=np.eye(10)

In [28]:
newarray

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
newarray=np.linspace(1,10,3)

In [32]:
newarray

array([ 1. ,  5.5, 10. ])

In [33]:
newarray=np.arange(1,10,2)

In [34]:
newarray

array([1, 3, 5, 7, 9])

In [35]:
newarray=np.arange(0,10,2)

In [36]:
newarray

array([0, 2, 4, 6, 8])

In [37]:
identity_matrix = np.eye(4)
print(identity_matrix)
# Output: [[1. 0. 0. 0.]
#          [0. 1. 0. 0.]
#          [0. 0. 1. 0.]
#          [0. 0. 0. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
linspace_arr = np.linspace(0, 10, 5)
print(linspace_arr)
# Output: [ 0.   2.5  5.   7.5 10. ]


[ 0.   2.5  5.   7.5 10. ]


In [39]:
arange_arr = np.arange(0, 10, 2)
print(arange_arr)
# Output: [0 2 4 6 8]


[0 2 4 6 8]


In [40]:
empty_arr = np.empty((2, 2))
print(empty_arr)
# Output: (Values uninitialized, could vary)


[[ 2.5  5. ]
 [ 7.5 10. ]]


In [42]:
newarray=np.random.rand(4,4)

In [43]:
newarray

array([[0.32353471, 0.5598931 , 0.13774308, 0.1178006 ],
       [0.80415533, 0.29348747, 0.98656438, 0.46227424],
       [0.2794237 , 0.97217952, 0.23639214, 0.53705326],
       [0.99936468, 0.75595612, 0.65294973, 0.79938184]])

In [46]:
newarray=np.random.randn(5,5)

In [47]:
newarray

array([[ 0.94675161,  0.05565651,  0.17997319,  0.44325372, -0.42251657],
       [-1.65667027, -0.85029128, -0.99079819,  0.87385867, -0.91753702],
       [ 2.37721883,  0.75994195,  0.99079807, -0.46609683,  0.15344307],
       [-0.37887344,  0.12780018, -0.50494537, -1.82124003,  0.49682674],
       [-1.29378699, -0.88822464,  1.22464742,  1.31143936,  1.94615059]])

In [51]:
newarray=np.random.randint(1,10,(5,5))

In [52]:
newarray

array([[1, 3, 1, 1, 5],
       [2, 1, 5, 2, 4],
       [7, 4, 2, 5, 5],
       [6, 2, 1, 9, 7],
       [3, 2, 1, 1, 4]])

In [53]:
newarray=np.random.choice([1,2,3,4,5,6] , size=(5,5))

In [60]:
newarray

In [63]:
newarray=np.random.shuffle([1,2,3,4,5,6])

In [64]:
print(newarray)

None


In [65]:
shuffle_arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(shuffle_arr)
print(shuffle_arr)
# Output: [4 5 2 1 3] (output varies)


[5 2 3 4 1]


In [67]:
newarray=np.random.rand(4,4)

In [68]:
newarray

array([[0.52904831, 0.46790823, 0.8926184 , 0.33424094],
       [0.8197487 , 0.59423674, 0.03364455, 0.19445261],
       [0.13874775, 0.2990845 , 0.97233516, 0.03959863],
       [0.58630452, 0.99715319, 0.34859654, 0.30163147]])

In [69]:
newarray=np.random.randn(4,4)

In [70]:
newarray

array([[ 1.27590228, -0.24901693,  0.96804402,  0.6054628 ],
       [ 0.35100882,  0.63011853, -0.54320048, -1.30315157],
       [-0.1384426 ,  0.95605819, -0.62465253,  0.2742235 ],
       [-1.45268291,  0.25575174, -0.34239281, -1.36105953]])

In [77]:
newarray=np.random.randint(1,100,(6,4))

In [78]:
newarray

array([[99, 63,  5, 30],
       [99, 87, 94, 29],
       [78, 66,  2, 21],
       [48,  6, 85, 77],
       [25, 54, 26, 76],
       [84, 32, 37, 73]])

In [79]:
newarray=np.random.choice([1,2,3,4,5,6,7,8,9,10] , size=(5,5))

In [80]:
newarray

array([[ 1,  9,  3,  8,  9],
       [ 9,  7,  9,  1,  7],
       [ 3,  6,  7,  8,  6],
       [ 2,  7,  5,  1,  1],
       [ 5,  1, 10,  8,  3]])

In [82]:
random_arr = np.random.rand(2, 3)
print(random_arr)
# Output: [[0.5314654  0.56942428 0.92111345]
#          [0.12859372 0.0137274  0.29803528]]


[[0.22851578 0.18001057 0.01448634]
 [0.2949655  0.63681548 0.29926699]]


In [83]:
random_int_arr = np.random.randint(1, 10, (3, 3))
print(random_int_arr)
# Output: [[8 3 1]
#          [9 5 8]
#          [1 5 2]]


[[9 2 9]
 [8 4 2]
 [6 3 8]]


In [84]:
random_normal_arr = np.random.randn(3, 3)
print(random_normal_arr)
# Output: [[-0.06281219  0.87939698 -0.0047966 ]
#          [ 0.20440502 -0.17145988  0.47985034]
#          [-0.29096073  1.39247374  0.4746671 ]]


[[-0.48204472  0.69978034  1.89258363]
 [-1.26615148 -0.77335629  0.58628842]
 [-1.52273335 -1.53011313 -0.08499433]]


In [85]:
choice_arr = np.random.choice([1, 2, 3, 4, 5], size=3)
print(choice_arr)
# Output: [4 1 3] (output varies)


[1 2 4]


In [86]:
shuffle_arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(shuffle_arr)
print(shuffle_arr)
# Output: [4 5 2 1 3] (output varies)


[4 1 5 3 2]


In [87]:
np.random.seed(42)
random_seeded_arr = np.random.rand(2, 2)
print(random_seeded_arr)
# Output: [[0.37454012 0.95071431]
#          [0.73199394 0.59865848]]


[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
